### ISSUE TITLE
Upgrade GeoMesa SQL and enable Shapely support.

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#102]

**Comment by metasim** [comment]
@vpipkt Let's talk about this. I have a PR upgrading the Scala side to the latest GM; let's look into getting the Python upgraded too.

**Comment by vpipkt** [comment]
This is right up my alley. Let's chat

**Comment by metasim** [comment]
Addressed in https://github.com/locationtech/rasterframes/commit/a09b524004630836b178c8dd52de434eb0a90497
