### ISSUE TITLE
Add spatial relations to `PyRFContext` functions

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#11]
Add `with org.locationtech.geomesa.spark.jts.DataFrameFunctions.Library` to `PyRFContext` declaration.

cc: @courtney-whalen @bguseman

**Comment by metasim** [comment]
To test it in Python, take some hints from the Scala tests in `astraea.spark.rasterframes.JTSSpec`.

**Comment by bguseman** [comment]
Still need to test this before closing

**Comment by courtney-whalen** [comment]
Just tested this in RFAI in Python notebook. Still getting below error:

![screen shot 2018-05-18 at 10 35 46 am](https://user-images.githubusercontent.com/33287843/40240990-db69d3b6-5a87-11e8-8116-5fc4d44872df.png)

**Comment by bguseman** [comment]
@courtney-whalen Unfortunately, these changes to not propagate through to RFAI automatically at this point. The pure rasterframes-notebooks will have this, and I will need to test it there before getting a new build ready for RFAI
