### ISSUE TITLE
Implement `rf_reproject(Raster)`

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#115]

**Comment by metasim** [comment]
Part of this capability is now implemented in `DataFrame.rasterJoin`.

**Comment by metasim** [comment]
The way of handling this from a DataFrame perspective is through the `toLayer` extension on `DataFrame`.

**Comment by karimbahgat** [comment]
Would like to bump this request, I can't seem to find any method or function that reprojects a raster from one crs to another, which I find odd for an explicit raster library. I'm still new to rasterframes however and hope I'm wrong, and that someone can point me to the right solution, example, or link?

**Comment by karimbahgat** [comment]
@metasim could you elaborate on how one would do this using `toLayer`, maybe with an example and/or links to documentation?
