### ISSUE TITLE
docker `rasterframes-notebooks` enhancements

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#12]
Observations from just poking around at it for a few minutes:

1) Tag an image as `latest` on dockerhub
2) Publish tagged 0.6.1 latest stable release
3) [This line](https://github.com/locationtech/rasterframes/blob/develop/deployment/docker/jupyter/Getting%20Started%20with%20RasterFrames.ipynb?short_path=5057f30#L68) of get started notebook should reference relative path `samples/L8-B4-Elkton-VA.tiff` not `../samples/`
4) Following initial instructions `docker run -it  --rm -p 8888:8888 s22s/rasterframes-notebooks:0.6.2-SNAPSHOT` the spark UI link shown in cell output is not available as expected. I ran with:

``` bash
docker run -it  --rm -p 8888:8888 -p 4040-4044:4040-4044 s22s/rasterframes-notebooks:0.6.2-SNAPSHOT
```
The link is still broken but i can go to `localhost:4040` instead. 
I also tried `--network=host` in my `docker run` command but that did not fix the issue. 

5) Set up some examples on a  "full size" multiband raster (e.g. landsat scene, modis granule, naip doqq) 
   1) data access options: build GeoTIFF file into docker image; host on s3(?) or somewhere user can publicly download using cell magic `!wget http://somewhere.io/file.tiff`
  
6) companion scala notebook on skylon kernel

**Comment by bguseman** [comment]
Items 1, 3, 4, and 6 are resolved (thank you @vpipkt).
