### ISSUE TITLE
Python 2 back compatibility with type hints

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#126]
Type annotations for Python 3 cause problems for Python 2 and earlier versions of Python 3 (before 3.5).

See [PEP-484](https://www.python.org/dev/peps/pep-0484/), we should 1) make sure to require the `typing` library which does nothing after 3.5; and 2) use comment style type annotations.

We could also decide to pre-emptively sunset support for Python 2.7. It's end of life is [Jan 1 2020](https://www.python.org/dev/peps/pep-0373/).

**Comment by vpipkt** [comment]
Also with PR https://github.com/locationtech/rasterframes/pull/125  I see we are going to try to get Python 3 support into the build system, presumably accelerating our move to sunset 2.7.

**Comment by metasim** [comment]
@vpipkt Do we still want to worry about this, given the PySpark roadmap?

**Comment by vpipkt** [comment]
I would think probably at this point we can just move forward with python
3. It would be nice to have a plan in place. Perhaps we put a stake in the
ground at version 0.9.0 will require python 3?

**Comment by metasim** [comment]
Closing in lieu of #317
