### ISSUE TITLE
Improve performance of CRS comparison in `rf_reproject`

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#134]
In large jobs, `rf_reproject` spends more time determining if two CRSs are equal than actually transforming geometry. This stack trace is typical:

```
scala.collection.mutable.HashTable$class.$init$(HashTable.scala:59)
scala.collection.mutable.HashMap.<init>(HashMap.scala:41)
scala.collection.mutable.HashMap.<init>(HashMap.scala:56)
scala.collection.mutable.Map$.empty(Map.scala:61)
scala.collection.TraversableLike$class.groupBy(TraversableLike.scala:319)
scala.collection.mutable.ArrayOps$ofRef.groupBy(ArrayOps.scala:186)
geotrellis.proj4.CRS$class.toProj4Map$1(CRS.scala:208)
geotrellis.proj4.CRS$class.compareProj4Strings(CRS.scala:213)
geotrellis.proj4.CRS$class.equals(CRS.scala:197)
org.locationtech.rasterframes.model.LazyCRS.equals(LazyCRS.scala:37)
geotrellis.proj4.Proj4Transform$.apply(Transform.scala:31)
geotrellis.proj4.Transform$.apply(Transform.scala:25)
org.locationtech.rasterframes.jts.ReprojectionTransformer.transform$lzycompute(ReprojectionTransformer.scala:34) => holding Monitor(org.locationtech.rasterframes.jts.ReprojectionTransformer@1409483535})
org.locationtech.rasterframes.jts.ReprojectionTransformer.transform(ReprojectionTransformer.scala:34)
org.locationtech.rasterframes.jts.ReprojectionTransformer$
```

`LazyCRS` helps, but only if both sides are `LazyCRS`.

cc: @vpipkt

**Comment by metasim** [comment]
## Before `LazyCRS` Optimization

<img width="1110" alt="Screen Shot 2019-06-06 at 8 42 39 AM" src="https://user-images.githubusercontent.com/131013/59033648-25c8b480-8837-11e9-92cd-d17d5ef65a87.png">

## After `LazyCRS` Optimization

<img width="1108" alt="Screen Shot 2019-06-06 at 8 44 40 AM" src="https://user-images.githubusercontent.com/131013/59033729-5ad50700-8837-11e9-91c0-48e327262004.png">

## Current Performance

_Added additional measures and renamed `logicalEquals` to `logicalEqualTrue`, and `selfEquals` to `logicalLazyEqualsTrue`._

<img width="1132" alt="Screen Shot 2019-06-06 at 8 42 00 AM" src="https://user-images.githubusercontent.com/131013/59033657-2eb98600-8837-11e9-9a0e-9afef47754ff.png">

**Comment by vpipkt** [comment]
interesting. i have some questions of a  nitpicky variety  about the charts.

**Comment by metasim** [comment]
@vpipkt Charts are via https://jmh.morethan.io/

**Comment by metasim** [comment]
After https://github.com/locationtech/rasterframes/pull/137/commits/dc561dc9ad49eca043a6a0465f11d18d09566db1:

<img width="1138" alt="Screen Shot 2019-06-06 at 9 53 32 AM" src="https://user-images.githubusercontent.com/131013/59038605-47c73480-8841-11e9-86e1-bedd7ec2319b.png">

**Comment by metasim** [comment]
Ideally we need to implement a means of speeding up the `false` case. Cache the comparison?

**Comment by metasim** [comment]
Closing for now... Obviously more work can be done, but this is a step in the right direction.
