### ISSUE TITLE
Tests fail under Python 2 but are not detected as such.

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#136]
@metasim 

One point of order. 

Travis build passes but it never actually runs the Python tests. It dies on trying to import pathlib. which I suspect means it is actually running python 2.7, but not sure.

So two issues there 

1. make the python tests correctly return as failed. 
2. more travis tweaking to run on python 3 if that's what we want.

https://travis-ci.org/locationtech/rasterframes/builds/541817162#L4430-L4434

_Originally posted by @vpipkt in https://github.com/locationtech/rasterframes/pull/133#issuecomment-499501864_

**Comment by vpipkt** [comment]
Duplicates #135

**Comment by vpipkt** [comment]
Smells like #40

**Comment by metasim** [comment]
oooof! Looks like I accidentally killed the functionality we had to detect this.

Need to reinstate this:

https://github.com/locationtech/rasterframes/blob/405c35e6d0ecb5282523805c89c34ca76a334756/pyrasterframes/build.sbt#L161-L207
