### ISSUE TITLE
Refresh geotiff writing capability

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#145]
Currently it is possible to [write a geotiff](https://github.com/locationtech/rasterframes/blob/develop/datasource/src/main/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffDataSource.scala#L67), but only if it has the spatial key and various metadata bits defining a GT Layer.  

As the API is shaping up now, we are getting away from that and making `rastersource` reads the mainstream in the API, and that schema is not restricted to GT Layer. This is becoming the case because it is difficult to maintain the metadata as the dataframe is mutated.

However it would be advantageous still to have some ability to create a GT layer from a dataframe, with some guardrails.  I would still prefer (especially in Python API) to see work with something like this  `df.write.geotiff.save(file)`. Under the hood it may:

* check that crs is either undefined or is unique across rows.
* use rf_extent to find overall extent of dataframe's spatial coverage
* deal with possibly heterogeneous tile dimensions
* set up GT Raster etc as appropriate and write GeoTiff

**Comment by vpipkt** [comment]
After thinking about this, a few further refinements come to mind.

I would be biased to writing at full resolution, at least in initial implementation.

I would also be open to a solution that writes a [hdfs_directory | s3_prefix] full of geotiffs, in such a fashion that a user could create a VRT out of them (after user does `hdfs get` or `aws s3 sync`). This puts some interesting restrictions on the outputs.

**Comment by metasim** [comment]
For GT layers, the pattern would be `df.write.geotrellis.save(file)`.

It's implemented here, but doesn't look like it's exposed in Python or via a Scala extension method (only through `.format("geotrellis")`.

https://github.com/locationtech/rasterframes/blob/3538bda126d885e3daa8b3913a82b3890a78da23/datasource/src/main/scala/org/locationtech/rasterframes/datasource/geotrellis/GeoTrellisLayerDataSource.scala#L75-L112

**Comment by metasim** [comment]
Also: 👍 for removing any `spatial_key` assumption.

**Comment by vpipkt** [comment]
@metasim I believe this is closed with merging of #212
