### ISSUE TITLE
Add Spark 2.4.x compatibility

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#154]
Some of the `Expression` code (around `AttributeReference`) no longer works.

**Comment by jdenisgiguere** [comment]
That feature would be really nice! 

I look to see how complicated to provide a patch for the missing `inputsNullSafe` parameter of `ScalaUDF`.  I don't have the background to solve it quickly.

Do you have any insights or plan to solve it @metasim ?

**Comment by metasim** [comment]
@jdenisgiguere Thanks for your thoughts. I have some broad notion on how to deal with it (and to do so with backward compatibility to 2.3.x). There's a class called `VersionShims` with a bunch of nasty reflection hacks to provide cross version compatibility in this area. I just need to sit down and make it happen, and your having interest pushes that further. Feel free to take a stab at it, or get it started and I can carry the baton the rest of the way. Just know we need to be compatible with 2.3.x for a while too.

**Comment by metasim** [comment]
@jdenisgiguere 

FYI, progress is being made: https://github.com/locationtech/rasterframes/pull/381
