### ISSUE TITLE
RasterSource interpretation of file paths

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#169]
Assume we have a proper COG at /tmp/modis.tif.

`spark.read.rastersource('/tmp/modis.tif').count()`

Throws 

```
Error fetching data for [0,100000000e,646f6d2f706d742f,6669742e7369]
java.lang.UnsupportedOperationException: Reading '/tmp/modis.tif' not supported
```

Which is confusing and unhelpful.

The user meant

`spark.read.rastersource('file:///tmp/modis.tif').count()`

Can we 

1. Give a clearer error message that the uri was not understood, or
2. Look to see if the path starts with '/' and try prepending 'file://' ?

**Comment by metasim** [comment]
We should do #2.

**Comment by vpipkt** [comment]
I believe the current behavior is now that it won't throw an error but an empty dataframe is returned.

**Comment by metasim** [comment]
🤦‍♂

**Comment by vpipkt** [comment]
related... see docs/raster-write.pymd
