### ISSUE TITLE
Add full resolution GeoTiff writing example

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#228]
I would also like to see an example where we select a contiguous subset and write it out at full resolution and in native CRS. 

Just for completeness. 

I think that would be a quite common use case also. Consider for example writing out ML classification model predictions for an area intersecting a polygon.

_Originally posted by @vpipkt in https://github.com/locationtech/rasterframes/pull/212_

**Comment by vpipkt** [comment]
Probably depend on #224

**Comment by vpipkt** [comment]
related #331

**Comment by vpipkt** [comment]
In #430 I've at least discussed it.
