### ISSUE TITLE
Unexpected behavior for rf_local_add with nodata tiles

### ISSUE THREAD

**Issue by emc5ud** [locationtech/rasterframes#229]
Hi, I was playing around with `rf_local_add` and came across the following results. I expected that with local tile arithmatic, no_data + data = no_data.

This code snippet creates a tile with 0's and 1's, and a tile with all 0's. Then I set 1 as the no data value. This makes the tile with 0's and 1's to now have 0's and "no datas" . Finally, I add the tiles together. The tile with with 0's and 1's does have no data as expected, but the sum does not have any nodata.
```
tile_size = 100
x = Tile(np.eye(tile_size, dtype='int16'))
y = Tile(np.zeros((tile_size, tile_size), dtype='int16'))

rf = spark.createDataFrame(pd.DataFrame(data = 
        {'eye_tile': [x],
        'zero_tile': [y]}))

mask_ct = CellType('uint16').with_no_data_value(1)
masked_rf = rf.withColumn('eye_tile_nd', 
                           rf_convert_cell_type('eye_tile', mask_ct.cell_type_name)) \
              .withColumn('zero_tile_nd',
                          rf_convert_cell_type('zero_tile', mask_ct.cell_type_name)) \
              .withColumn('masked', rf_local_add('eye_tile_nd', 'zero_tile_nd'))
```
![image](https://user-images.githubusercontent.com/8228717/62318434-da630900-b469-11e9-9a9e-dcdbcce549b5.png)

However, when doing the sum directly on the tiles, I do get a result with nodatas. 
```
r = masked_rf.collect()
r[0].eye_tile_nd + r[0].zero_tile_nd
```
![image](https://user-images.githubusercontent.com/8228717/62318518-01213f80-b46a-11e9-8d35-d264859de677.png)

The second behavior is what I expected, but regardless I think the behavior should be consistent.

**Comment by vpipkt** [comment]
Indeed behavior in the `Tile` operators should be consistent with the column functions. 

@metasim what would you expect from GeoTrellis?

**Comment by metasim** [comment]
GeoTrellis Does this:

* https://github.com/locationtech/geotrellis/blob/a463c48e7470e4ecfc0ae0ac297133d8bd00d641/raster/src/main/scala/geotrellis/raster/mapalgebra/local/Add.scala#L33

RasterFrames changes that behavior here:

* https://github.com/locationtech/rasterframes/blob/b307809dc130bfea94aa157599703780b848be82/core/src/main/scala/org/locationtech/rasterframes/util/DataBiasedOp.scala#L54

I'm not sure why I had RasterFrames do that in this case. Likely a bad call. @vpipkt Do you agree it should be `data + nodata = nodata`?

**Comment by vpipkt** [comment]
@metasim yes I do agree `data + nodata = nodata` should be the expected behavior for local column functions.

For `rf_agg_local_*` ignoring NoData is still sensible.

**Comment by vpipkt** [comment]
Possibly root cause for #225
