### ISSUE TITLE
GDAL integration not being picked up in rf-notebooks.

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#232]
Using the code in https://github.com/locationtech/rasterframes/pull/235 the following code can be invoked in the notebook environement:

```python
from pyrasterframes.utils import *
spark = create_rf_spark_session()
gdal_version()
```

The current  result is 'not available'. It should be something like 

    GDAL version GDAL 2.4.1, released 2019/03/15

Note: To build and launch a notebook, run `sbt rf-notebook/startRFNotebook`

**Comment by metasim** [comment]
Looks like the GDAL install code in `build/circleci/Dockerfile` needs to be copied to `rf-notebook/src/main/docker/Dockerfile`.

**Comment by metasim** [comment]
@vpipkt Kinda got it working.... but not the right version of gdal :-/ :

<img width="449" alt="Screen Shot 2019-08-05 at 4 07 05 PM" src="https://user-images.githubusercontent.com/131013/62491925-452e8000-b79b-11e9-80b6-0cdd6347130a.png">

**Comment by vpipkt** [comment]
Closing as dupe. We'll move conversations to #193
