### ISSUE TITLE
Updated functions accepting a cell type to allow `CellType` class.

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#238]
@vpipkt We should fix this to accept the `CellType` class directly, and not have the user do `cell_type_name`.

_Originally posted by @metasim in https://github.com/locationtech/rasterframes/pull/230/files_

**Comment by vpipkt** [comment]
I've contributed to #230 

I will add some more unit tests to it once that branch merges develop back in.

**Comment by vpipkt** [comment]
Fixed. and demonstrated in docs. could still use a unit test or two.
