### ISSUE TITLE
Some raster output in docs have lots of noise.

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#243]
From the "GeoTIFFs" section of _Writing Raster Data_:

<img width="460" alt="Screen Shot 2019-08-05 at 4 23 54 PM" src="https://user-images.githubusercontent.com/131013/62492747-6ee8a680-b79d-11e9-8bb8-65060e3058bc.png">

From the "User Defined Functions" section of _NumPy and Pandas_:

<img width="487" alt="Screen Shot 2019-08-05 at 4 25 07 PM" src="https://user-images.githubusercontent.com/131013/62492863-a0fa0880-b79d-11e9-8d74-7b87856e1d81.png">

I think this one is intended, but it's a bit confusing as an example, I think.

**Comment by metasim** [comment]
If we have`rf_is_no_data` perhaps the second raster can be made more clear.

**Comment by vpipkt** [comment]
FWIW this is what I see in the the Geoitiff section building locally.

The tiff itself seems correct


![image](https://user-images.githubusercontent.com/7798319/62626168-c4839700-b8f4-11e9-95a4-60a2052cc645.png)

**Comment by vpipkt** [comment]
For what it's worth this is what i see in QGIS with no adjustments

Sort of typical for MODIS actually to have this kind of strange look to it if you don't do any adjustment to it.

![image](https://user-images.githubusercontent.com/7798319/62637098-d4a57180-b908-11e9-976c-5e6105d18ba8.png)

**Comment by vpipkt** [comment]
We have cleaned up the first image in the latest doc version by only looking at a single channel.

Trying to stack three bands of modis to create a true color image is not that easily done  😉 

![image](https://user-images.githubusercontent.com/7798319/62729884-dc3e4680-b9ec-11e9-90cf-cc8d53676b9a.png)
