### ISSUE TITLE
Overview Section Feedback

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#245]
1. You could add a sample DataFrame under "Context" section (after 1st paragraph). You have a sample DataFrame later on in the "Architecture" section, but maybe the same DataFrame without all the detail could be added here when you are introducing the DataFrame concept.
1. Graph supporting World Bank quote that shows expected explosion of data - some kind of line chart?
1. Why the lambda notation in the sample DataFrame in the tile columns?

**Comment by vpipkt** [comment]
@courtney-whalen i'd be interested to chat about how we might address the first item, and what is driving that. 

I'm looking for somethign for the second one

ANd the third i'm trying to simplify.

**Comment by vpipkt** [comment]
Addressing in #249

**Comment by vpipkt** [comment]
@courtney-whalen @metasim 

Here is a sample of the rendered docs as on PR #249 . I've gotten rid of the many `/` that were inserted unhelpfully by my text editor. 

![image](https://user-images.githubusercontent.com/7798319/62625575-8043c700-b8f3-11e9-9b2b-48a37ac397f7.png)

**Comment by courtney-whalen** [comment]
@vpipkt the first item isn't necessary. just a thought since that's where the DataFrame concept is introduced
