### ISSUE TITLE
Concepts Section Feedback

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#246]
1. I like the section on Cell Types - are these the only cell types that can be used in RasterFrames?
2. CRS:
  a. Is it useful to mention that GeoJSON files sometimes don't have a "crs" member and just default to 4326?
  b. I don't know how hard this would be to do, but some kind of visual that shows a single region reprojected to a couple different CRS and demonstrates how different projections distort the image would be interesting to me
3. It would be cool to have visuals showing scene, extent, tile, etc. and how they are related
4. The difference between extent and projected extent isn't totally clear to me
5. Projected raster - I don't think the "raster" concept is introduced yet. Might be useful to talk about that briefly first.

**Comment by vpipkt** [comment]
Some very good ones here. Credit @courtney-whalen

I would tend to shy away from generating our own fundamental cartography/gis content like 2b, but it could be useful to try to find some links. This is maybe too basic but easy to understand and light hearted, no trig https://geoawesomeness.com/best-map-projection/

Our this is pretty good in term of principles and viz . https://gisgeography.com/map-distortion-tissots-indicatrix/

**Comment by vpipkt** [comment]
I will break out item 3 it is a great idea but a heavier lift. Something quite similar was mentioned in #250

**Comment by vpipkt** [comment]
Addressing the rest in #249
