### ISSUE TITLE
Raster Catalogs Section Feedback

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#248]
1. "The _Catalog_ is input into the raster DataSource, described in the next page." -> "The _Catalog_ is input into the raster DataSource, described in the next page, which downloads the tiles from these URLs."
2. "All referenced rasters represent the same content type." <- By "content type", I guess you mean product/band combination. "type" makes me think of cell types from the concepts page. Maybe "band" needs to be added to the concepts page if this hasn't been introduced yet?
3. One-D
  a. What does "h04v09" mean?
  b. Looks like the dates are both April 9, 2018. Should this be datetime or am I reading it wrong?
4. Using External Catalogs
  a. What do you mean by "(or a transformation of)"?
  b. What metadata are you referring to?
5. Using Built-in Experimental Catalogs
  a. I'm not sure what you mean by "transforming" here? Loading into a DataFrame?
  b. Why are these experimental?
6. I think it could be useful to do a show as well as printSchema on at least 1 of these to help illustrate that these are just URLs not tiles

**Comment by vpipkt** [comment]
I am not sure what the plan is, if any to move the pds catalog from  `experimental` into `datasources` namespace proper. @metasim any thoughts on what might take to get there...
