### ISSUE TITLE
Reading Raster Data Page Feedback

### ISSUE THREAD

**Issue by courtney-whalen** [locationtech/rasterframes#250]
1. Would be cool to see the tile extents overlaid on the scene (if that's not too hard) when you talk about breaking the raster out into many arbitrary non-overlapping regions
	2. The URI formats table is all messed up in my site preview
	3. Lazy Raster Reads
		a. 2nd sentence trails off
		b. I think more explanation is needed on why lazy reading is useful
		c. Does rf_tile always request the realized tile from the lazy representation or just in the initial examples? Wording is a bit confusing here.
	4. Multiband Rasters
		a. How do you know which band is which index?

**Comment by vpipkt** [comment]
For #1 we plan to  show something like this in the updated getting started jupyter notebook 

https://nbviewer.jupyter.org/github/locationtech/rasterframes/blob/b97582859256ca88416e39a1728d1cc9ed1a0901/rf-notebook/src/main/notebooks/Getting%20Started.ipynb 

It doesn't have the imagery also but... 🤷‍♂

**Comment by vpipkt** [comment]
Reopening until #260 is merged. just for my sanity.
