### ISSUE TITLE
Visual for scene vs tile extents

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#252]
Some feedback from #246 

>It would be cool to have visuals showing scene, extent, tile, etc. and how they are related

and #250 

> Would be cool to see the tile extents overlaid on the scene (if that's not too hard) when you talk about breaking the raster out into many arbitrary non-overlapping regions

**Comment by vpipkt** [comment]
@metasim agree with milestone tag?

**Comment by vpipkt** [comment]
bumping to milestone 0.8.1 because it is very much nice to have but don't want to hold us up. we can also do docs releases much faster than code releases.

**Comment by vpipkt** [comment]
Here is a relatively quick way to do it.... Possibly we could ship code for this as part of the example notebooks in rf-notebook. [252_prototype.ipynb.zip](https://github.com/locationtech/rasterframes/files/3483831/252_prototype.ipynb.zip)


Rough outline

1. Select `rf_crs` and `rf_geometry` from rasterframe
2. toPandas
3. create geopandas GeoDataFrame
4. union all tile extents, stash away 
5. reproject original tif to mercator with rasterio **
6. Add geodataframe to folium map
7. Add mercator image (numpy array) to folium map (use union extents from 4)


![image](https://user-images.githubusercontent.com/7798319/62739306-7f4d8b00-ba02-11e9-84ca-7cf04ab5b3d2.png)



For production quality graphic we could probably just do the geometry overlay in QGIS with the original and take a screen capture at fairly high res...

For a more convincing interactive  in a notebook environment.
1. start with *small* and *mercator projected* raster ; spark.read.raster('/path/to/mercator.tif')  
2. rf.select(rf_crs('pr'), rf_tile('pr')).toPandas() 
3.  geopandas GeoDataframe
4. Add each extent shape and tile image to map using `GeoDataFrame.apply`
     - Get extent in mercator, convert to WGS84 / EPSG4326
     - map.addChild(folium.GeoJson(extent_4326))
     - map.addChile(folium.raster_layers.ImageOverlay(image=tile.cells, bounds=extent_4326))

**Comment by vpipkt** [comment]
@courtney-whalen ☝️

**Comment by courtney-whalen** [comment]
looking good! this is what I had in mind for that visual

**Comment by vpipkt** [comment]
IMplementing this in docs would be aided by #302

**Comment by vpipkt** [comment]
Related #342

**Comment by vpipkt** [comment]
With merge of #430 we can easily generate a (downsampled) web-mercator projected Tile [.cells ndarray] and render on folium.

May make sense to hide the code implementation of the visual.
