### ISSUE TITLE
Publish 0.8.0 artifacts

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#278]
* [x] JVM Artifacts
* [x] PyPi Artifacts
* [x] Docker image
* [x] Documentation

**Comment by metasim** [comment]
@vpipkt Are there credentials necessary for PyPi publishing?

**Comment by vpipkt** [comment]
@metasim RE PyPi, yes [here](https://pypi.org/account/register/). I would recommend you registering with probably same email that you have linked to eclipse? But I don't think it matters terribly.

**Comment by vpipkt** [comment]
FWIW you can see how it will look on PyPi here, https://test.pypi.org/project/pyrasterframes/ 

Note all teh meta info on the left pane. Astraea is listed as teh author and I am the maintainer because I uploaded the wheel under my (test) account.

**Comment by metasim** [comment]
Account created.

**Comment by metasim** [comment]
Steps performed:

1. Used git-flow to create 0.8.0 release  branch.
2. Manually edited `version.sbt` and `version.py` to set value to `0.8.0`. Note: Release plugin needs updating so we can have this done automatically.
3. `sbt` shell commands:
  a. `clean`
  b. `test it:test`
  c. `publishSigned` (currently I'm the only one with the key to do this)
  d. `sonatypeReleaseAll`. It can take a while, but should eventually show up [here](https://search.maven.org/search?q=g:org.locationtech.rasterframes)
  e. `makeSite`
  f. `docs/ghpagesPushSite`
  g. `rf-notebook/docker:publish`
