### ISSUE TITLE
Update time-series.pymd to only use DataFrame API

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#288]
This will help tease out problems with literal/column type mismatching in Python.

**Comment by vpipkt** [comment]
Some interesting initial reactions.

1) we can easily add the __url__ to SparkFiles: `spark.sparkContext.addFile(nps_data_query_url)` which does not complain
    1) But it does not actually seem to be added; it's unclear what the filename actually is; the `SparkFiles.getRootDirectory()` dir is empty...

1) We can still download to /tmp and read... we'll work it that way for now. Makes things nicer for #285

**Comment by vpipkt** [comment]
Now reading this particular response with geojson reader gives us 

```
Py4JJavaError: An error occurred while calling o266.load.


: org.apache.spark.SparkException: Job aborted due to stage failure: 

Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): 

org.locationtech.jts.io.ParseException: Could not parse Geometry from Json string.  No 'type' property found

```

**Comment by vpipkt** [comment]
Ahh can pass "f=geojson" versus "f=json" params to the server and it will give more like strict geojson... 👍

**Comment by vpipkt** [comment]
Related #283

**Comment by vpipkt** [comment]
This is overall pretty slow still. Will have to try it out in CI to see how it goes. I tried reducing the number of persists, no idea if that will help.
