### ISSUE TITLE
Add a `withBoundsLatLng` extension

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#32]
_From @vpipkt on March 19, 2018 17:17_

Remember the SAT analogies?

`withCenter` : `withCenterLatLng` :: `withBounds` : `withBoundsLatLng`

Would be useful for querying against an EPSG:4326 column

_Copied from original issue: s22s/raster-frames#65_

**Comment by metasim** [comment]
We need to define the semantics of this. Are we talking about reprojecting the bounding in EPSG:4326, or the corresponding bounding extent in WGS84?

**Comment by metasim** [comment]
_From @vpipkt on March 20, 2018 15:31_

I would think reprojecting the bounding into EPSG:4326. 

Some possible use cases:
* inspection of rows 
* filter or join on data read from GeoJSON
* filter or join on data from GeoMesa

**Comment by metasim** [comment]
The problem, as @mteldridge points out, is that a extent/bounding box in the native CRS is not necessarily (unlikely to be) a straight-edged polygon in the destination CRS, especially when dealing with things like Sinusoidal projections. This may not matter that much for inspection/visualization, but if you want to do filtering, it should be in the native CRS.

**Comment by metasim** [comment]
_From @vpipkt on March 20, 2018 19:30_

Fair and excellent point. 

For inspection users ought to prefer the withCenterLatLng which does not have the distortions that a polygon would.

And for querying there are some limited use cases where it might make sense to use a square polygon from naively reprojecting the vertices. What's the preference? Give some rope or encourage more robust patterns?

**Comment by metasim** [comment]
Potentially relevant approach to handling this: `geotrellis.spark.tiling.MapKeyTransform`

**Comment by vpipkt** [comment]
I think we can close this issue. For the use case of inspecting coordinates of tiles, tile centers are good. For querying reprojecting (now available as column function) and then performing spatial operation is preferred.

**Comment by metasim** [comment]
Thanks for the update.
