### ISSUE TITLE
Write GeoTiff docs page discuss 3-band

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#331]
Need to describe how one /three /many tile columns  are going to be interpreted in the writer.

**Comment by metasim** [comment]
Current implementation:

* 1, 2, 5 or more bands: greyscale
* 3 bands: RGB
* 4 bands: RGBA (when colorspace is RGB and 4 bands are provided, the last is implicitly interpreted as the alpha channel)

https://github.com/locationtech/rasterframes/blob/36be70056fa01001bc3df006a4ea5655640c2d58/datasource/src/main/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffDataSource.scala#L152-L155

**Comment by vpipkt** [comment]
Discussed this in #430
