### ISSUE TITLE
Add additional python packages to Docker image

### ISSUE THREAD

**Issue by metasim** [locationtech/rasterframes#347]
Current:

* `anaconda`
* `sphinx` 
* `nbsphinx`
* `shapely`
* `numpy`
* `folium`
* `geopandas`
* `geojsonio`

Add:

* `rasterio`
* `descartes`

**Comment by metasim** [comment]
@vpipkt Any others?

**Comment by vpipkt** [comment]
With these I think we will  have all the ones we reference in docs and therefore example notebooks; basing this off of the setup_requires in setup.py. I think we are good.
