### ISSUE TITLE
Geotiff Writer does not use the right number of pixels

### ISSUE THREAD

**Issue by jdenisgiguere** [locationtech/rasterframes#360]
### Expected situation

When I save a tile from a  `RasterFrameLayer` as `GeoTiff`, I would expect that the size of the pixel would be the same for the output `GeoTiff` than the `RasterFRameLayer`.

### Current situation

When I use a filter condition to keep only a tile from a  `RasterFrameLayer` and I write it as `GeoTiff`, the resulting `GeoTiff` has the number of pixels than the original image instead of the number of pixels of the tile.

### How to reproduce

See: https://gist.github.com/jdenisgiguere/980ca9f28d5ded5da0d30c39fea17e2f based on code provided by @metasim on gitter.im.

**Comment by metasim** [comment]
Here's where the actual pixel size is computed: 

https://github.com/locationtech/geotrellis/blob/990f146da8217450fe037daeb058bbdbb4a9075c/raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TiffTags.scala#L115-L116

So the bug is likely to do with the extent being used.
