### ISSUE TITLE
Add rf_agg_local_median aggregate function

### ISSUE THREAD

**Issue by emc5ud** [locationtech/rasterframes#412]
Similar usage as rf_agg_local_mean

**Comment by metasim** [comment]
@emc5ud We need to identify a "streaming median algorithm" or "rolling median algorithm" to implement. . Some cursory research resources:

* https://stackoverflow.com/questions/1309263/rolling-median-algorithm-in-c
* https://stackoverflow.com/questions/31432843/how-to-find-median-and-quantiles-using-spark
* http://infolab.stanford.edu/~datar/courses/cs361a/papers/quantiles.pdf

We temporarily, we might be able to just explode the tile and feed it into the built-in scalar [approxQuantiles  implementation](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/QuantileSummaries.scala).

**Comment by vpipkt** [comment]
This should be closed with #429
