### ISSUE TITLE
Error loading pipeline model

### ISSUE THREAD

**Issue by courtney-whalen** [locationtech/rasterframes#425]
When loading in a model `model = PipelineModel.load('model/water_decision_tree')`, I am getting the following error for PyRasterFrames version '0.8.4' and PySpark version '2.4.4'.

![Screen Shot 2019-11-18 at 4 04 07 PM](https://user-images.githubusercontent.com/33287843/69093737-115f2980-0a1d-11ea-93c4-df17bb7f0491.png)

**Comment by vpipkt** [comment]
pipeline had:

```
exploder = TileExploder()
noDataFilter = NoDataFilter() \
  .setInputCols(["ndwi"])
labelIndexer = StringIndexer() \
  .setInputCol("target") \
  .setOutputCol("indexedTarget")
assembler = VectorAssembler() \
  .setInputCols(['ndwi']) \
  .setOutputCol("features")
classifier = DecisionTreeClassifier() \
  .setLabelCol('indexedTarget') \
  .setFeaturesCol("features")
pipeline = Pipeline() \
  .setStages([exploder, noDataFilter, labelIndexer, assembler, classifier])
```

**Comment by vpipkt** [comment]
I have  a branch with 2 failing unit tests confirming the problem, here: https://github.com/s22s/rasterframes/commit/f55088664e1f235c68aed1d7497d05ff8206b8c8

See this for possible cause. Will research more. https://github.com/apache/spark/blob/master/python/pyspark/ml/wrapper.py#L243-L245

**Comment by metasim** [comment]
:-o
