### ISSUE TITLE
LazyCRS has incorrect OGC CRS WKT <geographic_crs_keyword>

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#438]
Pattern matching [fails](https://github.com/locationtech/rasterframes/blob/develop/core/src/main/scala/org/locationtech/rasterframes/model/LazyCRS.scala#L57) on the following legal values for OGC WKT:

* `GEOGCRS ` [See sec 8.1 of spec](http://docs.opengeospatial.org/is/18-010r7/18-010r7.html#63)
* `GEOGRAPHICCRS` - sec 8.1
* `PROJCRS`  [See sec 9.1](http://docs.opengeospatial.org/is/18-010r7/18-010r7.html#71)
* `PROJECTEDCRS`  [See sec 9.1](http://docs.opengeospatial.org/is/18-010r7/18-010r7.html#71)

Arguable if this should support `<geodetic crs keyword>` values `GEODCRS | GEODETICCRS`. I'm not sure if the downstream libraries  do.

**Comment by vpipkt** [comment]
Hmm i may be mixing things up with different versions of the spec. Looking deeper into it now.

**Comment by vpipkt** [comment]
Some background based on more research. 

RasterFrames  CRS WKT parsing relies on the geotrellis proj4 module, which it seems is a [port](https://github.com/locationtech/geotrellis/blob/master/proj4/about.html) of a [port](https://github.com/locationtech/proj4j)...

The `pyrasterframes` dependencies currently resolve to a proj version 6 which has much more robust support for:

* specifying projection [by urn](https://github.com/locationtech/proj4j/issues/23)
* latest versions of [WKT spec](https://github.com/locationtech/proj4j/issues/49)

Propose for now clarifying the use of "WKT1" in the error messaging.

**Comment by vpipkt** [comment]
Probably should mark this as won't fix and perhaps defer to some other discussion about plans around LocationTech proj4j and GeoTrellis's proj4 module. It would be awesome to be able to use the 2015 or 2018 standards.

**Comment by pomadchin** [comment]
hey @vpipkt you're welcome to create PRs / open discussions in the proj4j locationtech repo: we're proj4 maintainers (Eugene & me)! We'll try to merge & release whatever is important for you ASAP.

**Comment by pomadchin** [comment]
Also https://github.com/locationtech/proj4j/issues/23 is in our backlog, but I don't know when we'll have time to dive into it.

**Comment by vpipkt** [comment]
@pomadchin Sorry for the slow response. Very interesting. I think we can close this issue in favor of the related issues already cited here.
