### ISSUE TITLE
v0.9.0-RC2 misses dependency on geotrellis-s3-spark

### ISSUE THREAD

**Issue by jdenisgiguere** [locationtech/rasterframes#467]
rasterframes `v0.9.0-RC2` doesn't have `geotrellis-s3-spark` in its dependencies list.
This makes impossible to load some Geotrellis Layer stored on `S3`.

Adding the dependency makes Geotrellis Layer stored on `S3` available.

A pull request will follows shortly.

**Comment by vpipkt** [comment]
@jdenisgiguere do the merged / cherry picked commits resolve the issue? Should we close this?

**Comment by jdenisgiguere** [comment]
@vpipkt , yes, this fixes it. Thanks!
