### ISSUE TITLE
rf_tile_to_array_int returns Double

### ISSUE THREAD

**Issue by jdenisgiguere** [locationtech/rasterframes#473]
## Current situation
`rf_tile_to_array_int` returns a Spark SQL Column of Array[Double].

https://github.com/locationtech/rasterframes/blob/release/0.9.0-RC2/core/src/main/scala/org/locationtech/rasterframes/functions/TileFunctions.scala#L50-L52

## Expected situation
`rf_tile_to_array_int` shall return a Spark SQL Column of Array[Int].

**Comment by metasim** [comment]
* [ ] TODO: cherry pick to `develop` and `gt-3.0`.
