### ISSUE TITLE
local map algebra functions with bands of different sizes

### ISSUE THREAD

**Issue by Atika9** [locationtech/rasterframes#475]
when I try to run rf_local_add or rf_local_subtract functions with two bands of different sizes as a parameter, I get this error:

``
Caused by: geotrellis.raster.GeoAttrsError: Cannot combine rasters with different dimensions.(512,512) does not match (256,256)
	at geotrellis.raster.package$TileTupleExtensions.assertEqualDimensions(package.scala:144)
	....`
``

**Comment by vpipkt** [comment]
This is expected behavior. You can use the [`rf_rescale`](https://rasterframes.io/reference.html#rf-resample) function to make one of the tiles have the same dimension as the other.

@Atika9 let me know if this solves your issue.

**Comment by Atika9** [comment]
@vpipkt  Thank you. 
Yes, the problem is solved using rf_resample function.

**Comment by vpipkt** [comment]
@Atika9 I'll go ahead and mark the issue resolved. Feel free to @ me if you think we need to revisit it.
