### ISSUE TITLE
from pyrasterframes.utils import gdal_version print(gdal_version()) not available

### ISSUE THREAD

**Issue by tieuthienvn1987** [locationtech/rasterframes#481]
I installed gdal version 3.0.2

**Comment by metasim** [comment]
@tieuthienvn1987 Right now RasterFrames is only compatible with GDAL 2.4.x.

**Comment by metasim** [comment]
@tieuthienvn1987 Here's where the version requirements are in the manual, but probably wouldn't hurt for us to make this a bit more clear:

 https://rasterframes.io/getting-started.html#installing-gdal-support

Do you need something in 3.0.2 or does this hold you for now? Would probably require a re-release of https://github.com/geotrellis/gdal-warp-bindings and https://github.com/locationtech/geotrellis

@pomadchin do you know which version of GDAL was used in 1.0.0 of `gdal-warp-bindings`. I know that if it was compiled with 2.x it is *not* forward compatible. Not sure about backwards compatibility.

**Comment by metasim** [comment]
Need to upgrade whole tool chain to GDAL 3.x
