### ISSUE TITLE
`g8` - raster frames version and  log file error

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#5]
Default version of RasterFrames in g8 template is 0.6.0, please bump to latest release

Also add dependency to rasterframes-datasource

Running `sbt new s22s/raster-frames.g8` as in the quick start results in the following error message:

```
Exiting due to error in the template
File: /var/folders/rz/ns09ztc12zbb44t5vcjfswdr0000gp/T/giter8-144181631187481/src/main/g8/src/main/resources/log4j.properties, 33:55: '=' came as a complete surprise to me
```

This seems to be due to the combination of `$` followed by `=` in the properties file.  Removing those lines allows the template to complete ok.

**Comment by metasim** [comment]
g8 templates have been abandoned.
