### ISSUE TITLE
`normalizedDifference` implicit conversion to float 

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#50]
As with the local arithmetic functions, desired behavior of `normalizedDifference` would be to first convert integer tiles to float type before computation. Otherwise computations such as NDVI which are defined on real numbers [-1, +1] will return one of -1, 0, or +1.

**Comment by metasim** [comment]
@vpipkt Are you thinking that if both the numerator an denominator are of an integral type, they should be auto coerced to `FloatCellType`? But if they are already `Float` or `Double` then pass through as is?

IOW, if `Float` or `Double`, leave as is, but otherwise convert to `Float`?

**Comment by vpipkt** [comment]
If _either_ tile argument is integral type the function should coerce them to floating point. 

Basically the division operation (what makes it normalized) only ever makes sense with continuous numbers; the addition and subtraction could be ok but potentially suffer some loss of precision if not treated as continuous.
