### ISSUE TITLE
Make pyrasterframes pip Installable

### ISSUE THREAD

**Issue by jbouffard** [locationtech/rasterframes#53]
From the [current README](https://github.com/locationtech/rasterframes/tree/develop/pyrasterframes/python#pyrasterframes), it appears that the only way to install `pyrasterframes` is to do so from source. This makes integrating `pyrasterframes` into other projects such as it `GeoPySpark` a bit more challenging as setting up the environment for `GeoPySpark` to run becomes more complicated.

While not a perfect solution, we have devised a method to [install GeoPySpark via pip](https://github.com/locationtech-labs/geopyspark#installing-from-pip) that may work for `pyrasterframes`.

**Comment by vpipkt** [comment]
@jbouffard I'm interested in your experience with the backend jar being too large for the pip package. Is the limitation on size of a single JAR? I ask because the current [pyspark tar.gz](https://pypi.org/project/pyspark/2.4.3/#files) is 206MB and contains 227 individual JARs.

**Comment by vpipkt** [comment]
It seems that pyspark itself presents a pattern we may be able to use. I think three elements are important.

1. In `setup.py` declaring a [package `${PACKAGE}.jars`](https://github.com/apache/spark/blob/master/python/setup.py#L186) 
2. [`package_dir`](https://github.com/apache/spark/blob/master/python/setup.py#L193-L194) and [`package_data`](https://github.com/apache/spark/blob/master/python/setup.py#L202-L203) args which define the `${PACKAGE}.jars`  
3. Including a [`jars` dir in MANIFEST.in](https://github.com/apache/spark/blob/master/python/MANIFEST.in#L18).  

I was able to mock this somewhat by creating a similar directory `deps/jars` within `pyrasterframes/target/python` and moving the assembly jar there. I then ran `python setup.py sdist` and then `pip install` the resulting tar.gz, all in a clean Python 3.6 environment. I do see the successful pip install and jar is under `${some_isolated_environment}/lib/python3.6/site-packages/pyrasterframes/jars/pyrasterframes-assembly-0.8.0-SNAPSHOT.jar`

I can then do `pyspark --jars ${some_isolated_environment}/lib/python3.6/site-packages/pyrasterframes/jars/pyrasterframes-assembly-0.8.0-SNAPSHOT.jar` and I can work with rasterframes successfully in local mode. Yay!

 
Of course now there is an interesting task of trying to ease the process of figuring out where that jar is. Both GeoPySpark and GeoMesa provide functions to help find the jars and set up an appropriate spark conf. PySpark has a little script that also gives a tip in the pip installed case, something [like this](https://github.com/apache/spark/blob/master/python/pyspark/find_spark_home.py#L54-L59) may work. In a plain `python` (not pyspark) interpreter in my pip installed environment:

```python
import os
from importlib.util import find_spec
from pyspark.sql import SparkSession
import pyrasterframes
jar_path = os.path.join(os.path.dirname(find_spec("pyrasterframes").origin), 'jars')
pyJar = ','.join([f.path for f in os.scandir(jar_path) if f.name[-3:] == 'jar'])
spark = (SparkSession.builder
            .master("local[*]")
            .appName("RasterFrames")
            .config('spark.driver.extraClassPath', pyJar)
            .config('spark.executor.extraClassPath', pyJar)
            .config("spark.ui.enabled", "false")
            .withKryoSerialization()
            .getOrCreate()
             ).withRasterFrames()
```

So we can provide a correctly configured local pyspark SparkSession in the pip installed case. It's a bit of a toss up to me whether we provide a convenience that gives a spark conf versus the more limited case of a pip only local only SparkSession. There are a lot of different deployment cases that providing a spark conf implies, versus something limited but that just works. 

Will put up a branch / wip pr soon...

**Comment by jbouffard** [comment]
Hey, @vpipkt! I am so sorry for just getting back to you now. I've been tasked with a new set of work and haven't really had the time to look into GPS and Python related issues :disappointed: 

In regards to question, you are correct that the size of the jar is what prevents us from putting it on PyPi. PyPi has a size restriction on the files that you can upload, but you can ask them to make exceptions which is probably what Apache did. However, they never ended up getting back to us :confused: This has caused us to implement a sort of roundabout way of getting the jar setup after the user `pip install`s GPS. It's definitely not ideal, and we would like to figure out a better system of distributing it.

The process that you stated of including the jar with the `whl`, `egg`, and/or `zip` file is correct; and that's the way I went when developing GPS. As for finding the jar, that can be tricky. We found that's it good to create a `SparkConf` with some predefined fields, but allow the user to add things as well. This gives flexibility while still providing an easy way to set up the environment. Here's the [function](https://github.com/locationtech-labs/geopyspark/blob/master/geopyspark/__init__.py#L45) that creates the `conf`.

**Comment by vpipkt** [comment]
@jbouffard Thank you so much. I am not sure what the limit is; rumors vary 60-100MB Our wheel is weighing in at about 59MB right now.  We have a PR open #144  on this now if you would like to take a look!

**Comment by jbouffard** [comment]
@vpipkt Don't mention it. I just looked over it and gave a similar suggestion of creating a function that produces a `SparkConf`. Otherwise, the PR is turning out well :slightly_smiling_face: I'm not sure how big our wheel was, but I know it was bigger than 60MB. I'll have to look into it again and see.
