### ISSUE TITLE
Errors of "FAILURE(3) CPLE_AWSInvalidCredentials(15) 'AWSInvalidCredentials.'" has occurred while running "Supervised Machine Learning".

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [locationtech/rasterframes#534]
Hi,
    Before I copied the codes and executed them, I have read the description about the "Supervised Machine Learning", which refers to "https://rasterframes.io/supervised-learning.html". However, I got the following errors:
"
FAILURE(3) CPLE_AWSInvalidCredentials(15) "AWSInvalidCredentials." AWS_SECRET_ACCESS_KEY and AWS_NO_SIGN_REQUEST configuration options not defined, and /root/.aws/credentials not filled 

py4j.protocol.Py4JJavaError: An error occurred while calling o142.collectToPython.
"
    After my searching on the Internet, I run the command to confirm whether the issue related about "AWS account".
![1](https://user-images.githubusercontent.com/72843232/103991744-13122080-51ce-11eb-9d60-3405f8fae2db.png)

    If the running "Supervised Machine Learning" needs "AWS account", then how to create the "AWS account"? Shall I access the "AWS" website and create my own username? So, could you pls give me some suggestions?

**Comment by vpipkt** [comment]
@JenniferYingyiWu2020 can you try setting `AWS_NO_SIGN_REQUEST=YES`? 

That is equivalent to the recommended options in the aws cli shown on the [landsat-pds page](https://registry.opendata.aws/landsat-8/)

See the following GDAL doc for more info: https://gdal.org/user/virtual_file_systems.html#vsis3-aws-s3-files

**Comment by JenniferYingyiWu2020** [comment]
@vpipkt , could you pls tell me how to set "AWS_NO_SIGN_REQUEST=YES"?

**Comment by JenniferYingyiWu2020** [comment]
@vpipkt , I used the local ".tif" image dataset, and "https://github.com/locationtech/rasterframes/raw/develop/pyrasterframes/src/test/resources/luray-labels.geojson". However, when I run the "Supervised Machine Learning", I got the following errors:
java.lang.IllegalArgumentException: Error fetching data for one of: GDALRasterSource(file:///home/jenniferwu/Raster_Data_Set/s22s-test-geotiffs/luray_snp/SCL.tif), GDALRasterSource(file:///home/jenniferwu/Raster_Data_Set/s22s-test-geotiffs/luray_snp/B01.tif), GDALRasterSource(file:///home/jenniferwu/Raster_Data_Set/s22s-test-geotiffs/luray_snp/B02.tif), GDALRasterSource(file:///home/jenniferwu/Raster_Data_Set/s22s-test-geotiffs/luray_snp/B03.tif), GDALRasterSource(file:///home/jenniferwu/Raster_Data_Set/s22s-test-geotiffs/luray_snp/B04.tif), GDALRasterSource(file:///home/jenniferwu/Raster_Data_Set/s22s-test-geotiffs/luray_snp/B05.tif), GDALRasterSource(file:///home/jenniferwu/Raster_Data_Set/s22s-test-geotiffs/luray_snp/B06.tif), GDALRasterSource(file:///home/jenniferwu/Raster_Data_Set/s22s-test-geotiffs/luray_snp/B07.tif), GDALRasterSource(file:///home/jenniferwu/Raster_Data_Set/s22s-test-geotiffs/luray_snp/B08.tif), GDALRasterSource(file:///home/jenniferwu/Raster_Data_Set/s22s-test-geotiffs/luray_snp/B09.tif), GDALRasterSource(file:///home/jenniferwu/Raster_Data_Set/s22s-test-geotiffs/luray_snp/B11.tif), GDALRasterSource(file:///home/jenniferwu/Raster_Data_Set/s22s-test-geotiffs/luray_snp/B12.tif)
![6](https://user-images.githubusercontent.com/72843232/104145104-c1051100-5400-11eb-918d-850c14471568.png)

**Comment by vpipkt** [comment]
@JenniferYingyiWu2020 i think the second issue regarding `java.lang.IllegalArgumentException: transpose requires all collections to have the same size` may be due to different resolutions / dimensions in the set of rasters given.

**Comment by JenniferYingyiWu2020** [comment]
OK, I got it, thanks!

**Comment by vpipkt** [comment]
It seems from this comment https://github.com/locationtech/rasterframes/issues/537#issuecomment-759884799 that the issue is resolved. If correct please close the issue, or let me know so I can close it.

**Comment by JenniferYingyiWu2020** [comment]
Of course, the issue has been resolved, which can be closed after confirmation.
