### ISSUE TITLE
How to make "Unsupervised machine learning" read "GeoTrellis Catalogs"?

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [locationtech/rasterframes#536]
Hi,
    I have read the "GeoTrellis Catalogs" section of "Reading Raster Data", 
![22](https://user-images.githubusercontent.com/72843232/104160277-d2174780-542b-11eb-933c-cd71afaa4a4b.png)

    However, the method of reading raster data used in "Unsupervised machine learning" is from reading 8 (bands) ".tiff" images by using file URI.
![24](https://user-images.githubusercontent.com/72843232/104160810-b3fe1700-542c-11eb-8de4-ef6a00ec12eb.png)

    So, could you pls give me some suggestions on how to modify the codes of "unsupervised machine learning" to read "GeoTrellis Catalogs"? Thanks!

**Comment by vpipkt** [comment]
What have you tried so far? Have you run into any behavior that you think is a bug?

I would think replace `df = spark.read.raster(...)` with `df = spark.read.geotrellis(...)` perhaps. This will depend on the specifics of how the geotrellis catalog has been ingested though. If you can provide additional details on the Gitter.im chat we'll try to help.
