### ISSUE TITLE
How to export the result of "Unsupervised Machine Learning" as GeoTIFFs?

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [locationtech/rasterframes#539]
Hi,
    I have seen the "Visualize Prediction" section that is under the "Unsupervised Machine Learning", and the resulting output is shown as below:
![1](https://user-images.githubusercontent.com/72843232/104555930-a4274280-5679-11eb-884c-eec24966c630.png)
    Also, I have read "GeoTIFFs" section of "Writing Raster Data", and the code "spark_df.write.geotiff" exports the GeoTIFFs.
![2](https://user-images.githubusercontent.com/72843232/104556142-008a6200-567a-11eb-836a-087d90fa324f.png)
    Now, my issue is that I'd like to export the "Visualize Prediction" result of "Unsupervised Machine Learning" as GeoTIFFs, but how to implement it? Could you pls give me some suggestions?

**Comment by vpipkt** [comment]
Is there a specific bug or error that you are encountering?

**Comment by JenniferYingyiWu2020** [comment]
Hi,
    I have used the codes “retiled.select('prediction', 'crs', 'extent').write.geotiff(<outfile name>, crs=<crs>)” on Supervised Machine Learning.
![1](https://user-images.githubusercontent.com/72843232/104886317-7eb17600-59a4-11eb-8365-d831eaaf5d26.png)
![2](https://user-images.githubusercontent.com/72843232/104886322-81ac6680-59a4-11eb-86c7-9363e40f0ec7.png)
    However, the output result is complete wrong. It is shown as below:
![Figure_1](https://user-images.githubusercontent.com/72843232/104886351-8e30bf00-59a4-11eb-8077-34aaa52d6755.png)
    My modified codes are followings:
![3](https://user-images.githubusercontent.com/72843232/104886382-9983ea80-59a4-11eb-8b89-77bea74c00c8.png)
    So, could you pls give me some suggestions why my output result using above codes generated a meaningless .tiff (shown as above)? Moreover, could you pls tell me how to resolve the issue? Thanks!

**Comment by JenniferYingyiWu2020** [comment]
Hi,
    After my modification the codes for output the result of GeoTIFFs as below, the the output result is still complete wrong.
![1](https://user-images.githubusercontent.com/72843232/104895912-6b58d780-59b1-11eb-83c1-13e59f5c21b2.png)
![image](https://user-images.githubusercontent.com/72843232/104895948-7875c680-59b1-11eb-9d7c-ac8ff03b14c4.png)

**Comment by vpipkt** [comment]
Can you share some details about your output if you [omit the `raster_dimensions` parameter](https://rasterframes.io/raster-write.html#downsampling)? 

Perhaps share the output of `gdalinfo` for the resulting output file? And if it is small enough attach to the issue?

**Comment by JenniferYingyiWu2020** [comment]
Hi,
    I have adopted your suggestion and omitted the "raster_dimensions" parameter, however, "java.lang.OutOfMemoryError: Java heap space" took place. Furthermore, I have replaced "raster_dimensions=(558, 507)" with "raster_dimensions=(5580, 5070)" or with "raster_dimensions=(1558, 1507)", the "java.lang.OutOfMemoryError: Java heap space" errors also appeared.
    A new project named "rasterframes-GeoTIFFs" has been created on my Github page. I have uploaded the "unsupervised machine learning" and "supervised machine learning (https://github.com/JenniferYingyiWu2020/rasterframes-GeoTIFFs/blob/main/machine-learning/supervised_machine_learning.py)" codes, also the error logs (https://github.com/JenniferYingyiWu2020/rasterframes-GeoTIFFs/tree/main/error-logs) while changing the "raster_dimensions".
The show output result of GeoTIFFs is: "https://github.com/JenniferYingyiWu2020/rasterframes-GeoTIFFs/blob/main/show-output-result/supervised-machine-learning/show.png".
![1](https://user-images.githubusercontent.com/72843232/104997933-63f30600-5a65-11eb-8324-94ed3a0f3bc5.png)

**Comment by JenniferYingyiWu2020** [comment]
Hi,
    Lastly, the output of gdalinfo for the resulting output .tiff generated by "supervised machine learning" is below. In that case, the "raster_dimensions" parameter is "raster_dimensions=(558, 507)".
![1](https://user-images.githubusercontent.com/72843232/104999663-322f6e80-5a68-11eb-8314-ad0be4c04954.png)

**Comment by vpipkt** [comment]
Please refer to extensive discussion on the [Gitter channel](https://gitter.im/locationtech/rasterframes?at=6006925dcf8b8277343d86b2) for more detail.

Here is the reason you see the "blocks" of output in the GeoTiff written.

At [line 101](https://github.com/JenniferYingyiWu2020/rasterframes-GeoTIFFs/blob/main/machine-learning/supervised_machine_learning.py#L101-L102) you `join` the input catalog named `df` with the `label_df`, and so filter only to rows containing these labels. 

Here is a visual of an input band (greyscale), the output prediction GeoTiff (viridis color scheme) and the label GeoJSON shapes (pink).

![image](https://user-images.githubusercontent.com/7798319/105054268-cc2ef100-5a3f-11eb-9687-1e397788109d.png)


The tiles that are written out [at line 225](https://github.com/JenniferYingyiWu2020/rasterframes-GeoTIFFs/blob/main/machine-learning/supervised_machine_learning.py#L225) are still filtered by the join with the `label_df`.

A suggested alternative would be something like the below. A further refinement would be to apply masking to the data, as on [lines 113-120](https://github.com/JenniferYingyiWu2020/rasterframes-GeoTIFFs/blob/main/machine-learning/supervised_machine_learning.py#L113-L120) before the `join`. 


```
model.transform(df).groupBy('extent', 'crs') \
    .agg(
    rf_assemble_tile('column_index', 'row_index', 'prediction', tile_size, tile_size).alias('prediction'),
    rf_assemble_tile('column_index', 'row_index', 'B04', tile_size, tile_size).alias('red'),
    rf_assemble_tile('column_index', 'row_index', 'B03', tile_size, tile_size).alias('grn'),
    rf_assemble_tile('column_index', 'row_index', 'B02', tile_size, tile_size).alias('blu')
   ) \
  .write.geotiff(outfile, crs=crs, raster_dimensions=(1830//4, 1830//4)))
``` 

This looks like so:

![image](https://user-images.githubusercontent.com/7798319/105056192-ee297300-5a41-11eb-8a30-6d5ded167ff4.png)


Of course, there is a conceptual with downsampling a discrete classification result like this, which is that the result at any pixel location will be somewhat arbitrary. As noted in [the docs](https://rasterframes.io/raster-write.html#downsampling),  the GeoTIFF writer uses Bilinear resampling.
