### ISSUE TITLE
How to show "the label GeoJSON shapes (pink)" on output .tiff? How to apply masking to the data, as on lines 113-120 before the join?

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [locationtech/rasterframes#541]
Hi,
    I have accepted your suggestions on https://github.com/locationtech/rasterframes/issues/539, and modified the codes of ["supervised machine learning"](https://github.com/JenniferYingyiWu2020/rasterframes-GeoTIFFs/blob/main/machine-learning/supervised_machine_learning.py), however my output ".tiff" is a little difference from yours on "https://github.com/locationtech/rasterframes/issues/539".
    Moreover, I have uploaded my output ".tiff" on [my repo](https://github.com/JenniferYingyiWu2020/rasterframes-GeoTIFFs/blob/main/show-output-result/supervised-machine-learning/show_version%200.2.png), in comparison with the output result on "https://github.com/locationtech/rasterframes/issues/539", which is [here](https://github.com/JenniferYingyiWu2020/rasterframes-GeoTIFFs/blob/main/show-output-result/supervised-machine-learning/vpipkt/github-reply.png).

![show_version 0 2](https://user-images.githubusercontent.com/72843232/105271158-ff08ee80-5bd1-11eb-896b-e0ee3ae80f7c.png)

![1](https://user-images.githubusercontent.com/72843232/105271172-04fecf80-5bd2-11eb-91d9-ff02d21eeb6d.png)

I feel the difference with the above two ".tiff" show is mine lost the "the label GeoJSON shapes (pink)". As on "https://github.com/locationtech/rasterframes/issues/539", you say that "A further refinement would be to apply masking to the data, as on lines 113-120 before the join.", but I am so confused about how to modify the codes?

So, could you pls give me some suggestions? Thanks!

**Comment by vpipkt** [comment]
The image with the pink GeoJSON shapes is simply showing the GeoJSON and the GeoTIFF together in QGIS.   The GeoTiff i wrote out is attached here: [unsupervised.zip](https://github.com/locationtech/rasterframes/files/5850432/unsupervised.zip)
