### ISSUE TITLE
How to reslove "java.lang.IllegalArgumentException: Error fetching data for one of: HadoopGeoTiffRasterSource(hdfs://192.168.101.201:9000/.../split_20200613clip/SCL.tif), ...)"

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [locationtech/rasterframes#552]
![1](https://user-images.githubusercontent.com/72843232/113671269-b8af3000-96e8-11eb-9d1a-40d4a31ccffb.png)
![2](https://user-images.githubusercontent.com/72843232/113671289-bfd63e00-96e8-11eb-92a0-e33ac0b31617.png)
![3](https://user-images.githubusercontent.com/72843232/113671313-c5cc1f00-96e8-11eb-800d-5ed1a299aa7b.png)
![4](https://user-images.githubusercontent.com/72843232/113671326-c9f83c80-96e8-11eb-9a0f-d5975f34923a.png)
![5](https://user-images.githubusercontent.com/72843232/113671348-cf558700-96e8-11eb-9a89-af5b172f5bd9.png)
![6](https://user-images.githubusercontent.com/72843232/113671371-d41a3b00-96e8-11eb-8f4b-cdac61fb5aa2.png)
![7](https://user-images.githubusercontent.com/72843232/113671383-d7adc200-96e8-11eb-912c-ea2464706c6d.png)
![8](https://user-images.githubusercontent.com/72843232/113671392-daa8b280-96e8-11eb-8ae9-e4e4ac5aea3a.png)
![10](https://user-images.githubusercontent.com/72843232/113671404-e005fd00-96e8-11eb-9d67-abaf05ba3a4b.png)

    So, could you pls help to give me some suggestions on how to resolve the above errors? Thanks!

**Comment by JenniferYingyiWu2020** [comment]
Moreover, I have tried 3 ways to install GDAL. However, the "java.lang.IllegalArgumentException: Error fetching data for one of: HadoopGeoTiffRasterSource" has always been encoutered.
    The first method is installing the latest GDAL using conda:
![1](https://user-images.githubusercontent.com/72843232/113672309-2445cd00-96ea-11eb-8277-951c1faec55f.png)
![2](https://user-images.githubusercontent.com/72843232/113672320-2740bd80-96ea-11eb-9b43-bc184c1a4298.png)
![3](https://user-images.githubusercontent.com/72843232/113675039-805e2080-96ed-11eb-8394-dcda47c449f5.png)
![4](https://user-images.githubusercontent.com/72843232/113675051-848a3e00-96ed-11eb-852c-5e008319fd1c.png)
![5](https://user-images.githubusercontent.com/72843232/113675068-88b65b80-96ed-11eb-87ff-7ef06f4507ef.png)
![6](https://user-images.githubusercontent.com/72843232/113675081-8ce27900-96ed-11eb-9c4c-bd83726e0806.png)
    Secondly, I change to install GDAL from source code:
![21](https://user-images.githubusercontent.com/72843232/113675221-b7343680-96ed-11eb-9df6-e612dfd59dde.png)
![22](https://user-images.githubusercontent.com/72843232/113675240-be5b4480-96ed-11eb-8ba8-5aae7648bd18.png)
![23](https://user-images.githubusercontent.com/72843232/113675256-c0bd9e80-96ed-11eb-9363-c67f27ebb972.png)
![24](https://user-images.githubusercontent.com/72843232/113675272-c5825280-96ed-11eb-8c1d-2bc900c5a5f1.png)
![25](https://user-images.githubusercontent.com/72843232/113675283-c87d4300-96ed-11eb-8694-b9afe7a631d4.png)
    In my local hadoop user environment, pyrasterframes has been installed using "pip" and GDAL has been installed using "conda":
![31](https://user-images.githubusercontent.com/72843232/113675508-02e6e000-96ee-11eb-8e0c-e94ec744f793.png)
![32](https://user-images.githubusercontent.com/72843232/113675525-08dcc100-96ee-11eb-94e4-ff574a515eac.png)
![33](https://user-images.githubusercontent.com/72843232/113675533-0d08de80-96ee-11eb-8521-38ffe6449cd5.png)
![34](https://user-images.githubusercontent.com/72843232/113675547-109c6580-96ee-11eb-85f7-832059aecd89.png)
![35](https://user-images.githubusercontent.com/72843232/113675579-172add00-96ee-11eb-8b03-b3b319ec6dfb.png)
![36](https://user-images.githubusercontent.com/72843232/113675592-1abe6400-96ee-11eb-9710-2388b0aed133.png)

**Comment by lepitrust** [comment]
anyone resolve this issue?
i have the same...

**Comment by JenniferYingyiWu2020** [comment]
Hi All, 
    I have resolved the issue by myself. So, after that, I will close the issue. Thanks!

**Comment by lepitrust** [comment]
> Hi All,
> I have resolved the issue by myself. So, after that, I will close the issue. Thanks!

Can you tell me how do you resolve? Thanks

**Comment by JenniferYingyiWu2020** [comment]
Yes, it is exactly that.
