### ISSUE TITLE
Tile contents from GeoTiff data source do not check-sum to expected contents

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#59]
I discovered this issue by  inspecting a raster with known properties: a gridded population raster's sum should be close to the official census values.

It seems that the problem may be in the GeoTiff Relation?

Observe the following commit: https://github.com/vpipkt/rasterframes/commit/f50eabab818c3d2aaa3001d1101ca6ee717cca38 

I computed the sum of the sample GeoTiff with python package rasterio; and in the `TileStatsSpec` the `RasterFrame` is built from a GeoTrellis `ProjectedRaster`.

However the sum of tile sums when reading the same GeoTiff with `spark.read.geotiff` does not match the expected result from rasterio & GeoTrellis.

**Comment by metasim** [comment]
Possible this might be related to #31, but the fact that the Hadoop reader handles this OK makes me suspect.

**Comment by metasim** [comment]
Curious statistical difference (or non-difference):

## `GeoTiffRelation`

dataCells|min   |max    |mean            |variance          
---------|------|-------|----------------|------------------
28561    |9261.0|20778.0|9834.60971254508|381596.47506968677



## Direct GeoTrellis Read

|dataCells|min   |max    |mean             |variance         |
|---------|------|-------|-----------------|-----------------|
|31434    |9261.0|20778.0|9834.874785264363|384987.7186217159|

@vpipkt Interested if you have any insightful interpretation here

**Comment by vpipkt** [comment]
So this is in fact consistent with our issue. The `mean` multiplied by the `dataCells` should in each case give us the same result as `sum(tileSum(t))`.

`GeoTiffRelation` 
```
scala> 28561 * 9834.60971254508
res1: Double = 2.80886288E8
```

`GeoTrellis Read`
scala> 31434 * 9834.874785264363
res2: Double = 3.09149454E8


Compare to the output of failing unit test for reference:

```
2.80886288E8 did not equal 309149454
ScalaTestFailureLocation: astraea.spark.rasterframes.datasource.geotiff.GeoTiffDataSourceSpec$$anonfun$1$$anonfun$apply$mcV$sp$4 at (GeoTiffDataSourceSpec.scala:96)
Expected :309149454
Actual   :2.80886288E8
```

I interpret this as meaning that there are cells in the GeoTiffRelation that are never being aggregated. 

I have another file that seems to suffer the opposite problem (it has celltype `float64raw`).

true datacells = 735,868; sum = 5,204,199.0; non-zero cells = 102,091
gtif datacells = 1,322,500; sum = 9,350,826

**Comment by metasim** [comment]
Thanks, that's helpful analysis. It may be that some portion of the data is being dropped. Digging in deeper to the Hadoop reader side.

**Comment by vpipkt** [comment]
FWIW
