### ISSUE TITLE
Support for Spark 3.0

### ISSUE THREAD

**Issue by DragonEnergy** [locationtech/rasterframes#593]
Need support for Spark 3.0+ integrations. Currently All Databricks Runtimes are now using  3.0

assembly.jar is only compatible for deprecated versions of spark from the databricks runtimes sub 3.0 versions of spark
https://github.com/locationtech/rasterframes/releases/tag/databricks-spark2.4-python3
https://github.com/locationtech/rasterframes/commit/eb40b6068557321657e0b15fe65e61fb7e7c55a6

**Comment by echeipesh** [comment]
Spark 3.1.2 is supported as of [release 0.10.0](https://github.com/locationtech/rasterframes/releases/tag/0.10.0)
