### ISSUE TITLE
Quickstart improvements

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#6]
In the documentation quick start I suggest adding a section on bringing up an interactive spark shell as an alternative to giter8 template or setting up existing project's dependencies. If someone is just checking out the library they should be able to run `sbt console` (or in python `sbt pysparkCmd` then run the given command). Then be able to follow along much of the rest of the documentation.

An issue that I have found within the `sbt console` spark shell, with this is when reading any ole geotiff off the street (e.g. full landsat scene, NAIP DOQQ, etc) of about 150MB - 200MB in size I get a Java heap space error. This seems like a very common thing to try, take a familiar and handy tif and see what it looks like in a dataframe. Can we change some configs to give more memory to avoid such issues? Running spark local on a reasonable size machine should be able to handle this size data.

**Comment by metasim** [comment]
With the new notebook option and a refined console experience, I suggest we disband the g8 template. @vpipkt Do you have an opinion on this?

cf: #5

**Comment by vpipkt** [comment]
I've never used g8, so no informed opinion about keeping it. It is one more
thing to maintain in release cycles.

**Comment by vpipkt** [comment]
Also should highlight published docker hub image fore rasterframes-notebooks in the quick start
