### ISSUE TITLE
Have pyrasterframes be Packaged as a wheel Rather Than an egg

### ISSUE THREAD

**Issue by jbouffard** [locationtech/rasterframes#62]
When assembling `pyrasterframes`, the Python library is packaged as an `egg` file (see [here](https://github.com/locationtech/rasterframes/blob/develop/pyrasterframes/build.sbt#L158)). However, the `Python Packaging User Guide` states that [wheel files should be used instead of eggs](https://packaging.python.org/discussions/wheel-vs-egg/) for various reasons. Therefore, it would be good to change the packaging format to `wheel`s.

I think all that's needed is to change `bdist_egg` to `bdist_wheel`. Though, that'll need to be tested to ensure that everything still works properly.

**Comment by bguseman** [comment]
Changed. The sbt task was adjusted to create a .whl and move it to a target location where other artifacts are placed
