### ISSUE TITLE
`spark.write.geotiff` round trip

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#68]
I am looking into using the geotiff writer and I discovered the following. A test resource geotiff (COG) is read and then without modification written in the `GeoTiffDataSourceSpec`.  The  output of the writer is distorted... I'll provide links to previews of the images as well as the output that I get for reference.

The output tif is larger, as entire tiles are written. It has the same datatype and nodata value for each band.

The gdalinfo output for both is below. The writer outputs a file named `example-geotiff.tiff`

```
$ gdalinfo core/src/test/resources/LC08_RGB_Norfolk_COG.tiff
Driver: GTiff/GeoTIFF
Files: core/src/test/resources/LC08_RGB_Norfolk_COG.tiff
Size is 1028, 989
Coordinate System is:
PROJCS["WGS 84 / UTM zone 18N",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",-75],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","32618"]]
Origin = (364455.000000000000000,4109985.000000000000000)
Pixel Size = (30.000000000000000,-30.000000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=DEFLATE
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  364455.000, 4109985.000) ( 76d31'33.12"W, 37d 7'35.07"N)
Lower Left  (  364455.000, 4080315.000) ( 76d31'13.92"W, 36d51'32.56"N)
Upper Right (  395295.000, 4109985.000) ( 76d10'43.57"W, 37d 7'49.33"N)
Lower Right (  395295.000, 4080315.000) ( 76d10'28.74"W, 36d51'46.68"N)
Center      (  379875.000, 4095150.000) ( 76d20'59.84"W, 36d59'41.37"N)
Band 1 Block=256x256 Type=UInt16, ColorInterp=Red
  NoData Value=0
  Overviews: 514x495, 257x248, 129x124, 65x62, 33x31
Band 2 Block=256x256 Type=UInt16, ColorInterp=Green
  NoData Value=0
  Overviews: 514x495, 257x248, 129x124, 65x62, 33x31
Band 3 Block=256x256 Type=UInt16, ColorInterp=Blue
  NoData Value=0
  Overviews: 514x495, 257x248, 129x124, 65x62, 33x31

$ gdalinfo example-geotiff.tiff
Warning 1: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
Driver: GTiff/GeoTIFF
Files: example-geotiff.tiff
Size is 1280, 1024
Coordinate System is:
PROJCS["WGS 84 / UTM zone 18N",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",-75],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","32618"]]
Origin = (364455.000000000000000,4109985.000000000000000)
Pixel Size = (24.093750000000000,-28.974609375000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  364455.000, 4109985.000) ( 76d31'33.12"W, 37d 7'35.07"N)
Lower Left  (  364455.000, 4080315.000) ( 76d31'13.92"W, 36d51'32.56"N)
Upper Right (  395295.000, 4109985.000) ( 76d10'43.57"W, 37d 7'49.33"N)
Lower Right (  395295.000, 4080315.000) ( 76d10'28.74"W, 36d51'46.68"N)
Center      (  379875.000, 4095150.000) ( 76d20'59.84"W, 36d59'41.37"N)
Band 1 Block=1280x3 Type=UInt16, ColorInterp=Gray
  NoData Value=0
Band 2 Block=1280x3 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
Band 3 Block=1280x3 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
```

**Comment by vpipkt** [comment]
I'm looking around a little bit and I see for the RasterFrame that's read it has heterogenous tile sizes:

```
+--------+--------+-----+
|tileRows|tileCols|count|
+--------+--------+-----+
|221     |4       |1    |
|221     |256     |4    |
|256     |4       |3    |
|256     |256     |12   |
+--------+--------+-----+
```

When writing, the following is used to set the default full resolution output size.

https://github.com/locationtech/rasterframes/blob/develop/datasource/src/main/scala/astraea/spark/rasterframes/datasource/geotiff/DefaultSource.scala#L59-L60

Looking at the gdal info you can see that it must be 5 by 4 tiles, and tile size is 256 thus you get `Size is 1280, 1024`

So the tile layer metadata is not reliable in this case of heterogenous tile sizes. One could just enforce homogenous tile sizes on reading if the cell type has NoData. But that would not solve the general problem.

Related to #31 ??  Which seems to have the opposite problem that homogenous tile sizes with NoNoData cell type results in improper values.

**Comment by vpipkt** [comment]
I was able to get the output rows and columns from the RasterFrame itself but the output is still incorrect.  It is now the correct number of rows and columns, and the pixel size is correct.

However the distortion still remains and the image looks quite similar.

The problem seems to be that the tile layer metadata from the GeoTiffRelation is arguably incorrect and certainly inconsistent with the actual Tile locations. It has the `Extent` of the input geotiff as its `Extent`. But TileLayerMetadata does not really understand heterogenous tile sizes, so when we try to recover the location of the Tile bounds or centers, they will necessarily be equally spaced in the total number of columns and rows.  However the heterogenous tile sizes means they are not actually so, because the Extent does not consider that.

So this is realated to #31. The case where there is NoData we can safely expand the Extent to capture the "overlap" of the last column or row - either by making the Tiles all the same size, or by recalculating the bounds. In the NoNoData case it is still difficult to generalize.

**Comment by metasim** [comment]
FWIW, The file I downloaded from drive is *not* a COG. Does't mean there's not a bug, just that it's in a different part of the code.

```console
$ validate_cloud_optimized_geotiff.py example-geotiff.tiff
example-geotiff.tiff is NOT a valid cloud optimized GeoTIFF.
The following errors were found:
 - The file is greater than 512xH or Wx512, but is not tiled
 - The file is greater than 512xH or Wx512, but has no overviews
```

**Comment by metasim** [comment]
Sorry, I was testing the wrong file. The test (input) file *is* a COG:

```console
$ validate_cloud_optimized_geotiff.py LC08_RGB_Norfolk_COG.tiff
LC08_RGB_Norfolk_COG.tiff is a valid cloud optimized GeoTIFF
```

It was the file that RF wrote that was not a COG.

**Comment by vpipkt** [comment]
Currently seeing some distortion in output  

![screen shot 2018-07-13 at 12 57 34](https://user-images.githubusercontent.com/7798319/42704049-73555fde-869c-11e8-8f29-747f8afc86db.png)
![screen shot 2018-07-13 at 12 57 43](https://user-images.githubusercontent.com/7798319/42704050-7362cc50-869c-11e8-91a4-f850361fab56.png)

**Comment by vpipkt** [comment]
Side by side:  https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=b56c070c-86be-11e8-b263-0edaf8f81e27

**Comment by metasim** [comment]
Thanks for the juxtapose view.... I never would have picked up on that.

**Comment by metasim** [comment]
@vpipkt If you had to guess, do you think this is a read-side error or a write side error?

**Comment by vpipkt** [comment]
I would say write side

**Comment by vpipkt** [comment]
@metasim can you re-open this issue?

**Comment by metasim** [comment]
This is being picked up by https://github.com/locationtech/rasterframes/pull/231
