### ISSUE TITLE
pyrasterframes read.geotrellis documentation

### ISSUE THREAD

**Issue by jdenisgiguere** [locationtech/rasterframes#89]
Greetings,

## Current situation

pyrasterframes expose a geotrellis reader. See:
https://github.com/locationtech/rasterframes/blob/e7209d312f7ce7af30a9c9c379532b2aff353e72/pyrasterframes/python/pyrasterframes/__init__.py#L54

I cannot find the syntax required to use it.

My current workaround is to use https://github.com/locationtech-labs/geopyspark/blob/d67f72c532d512f53eb18d9a0f2f8fd00ecced31/geopyspark/geotrellis/layer.py#L1235

## Expected situation

We should be able to use something like this.

```python
from pyspark.sql import SparkSession
from pyrasterframes import *

session = SparkSession.builder.appName("RasterFrameDemo").config("spark.ui.enabled", "false").getOrCreate().withRasterFrames()

rf = session.read.geotrellis({'uri': 'file:/data/my_catalog', 'layer_name': 'my_layer_name', 'layer_zoom': 0})

rf.printSchema()
```

**Comment by jdenisgiguere** [comment]
As reported by @metasim , there is an alternative syntax.

**Geotrellis Layer**

```python
layer = spark.read.format('geotrellis').load(path=uri, layer=layer_name, zoom=zoom_level)
```
where
* `uri` : URI as string;
* `layer_name` : the layer name as string;
* `zoom_level` : the zoom level as integer.

**Geotrellis Catalog**

```python
catalog = spark.read.format('geotrellis-catalog').load(uri)
```
where
* `uri` : URI as string.

**Comment by metasim** [comment]
Thanks @jdenisgiguere !!
