### ISSUE TITLE
`tileDimensions` function SQL and Python naming

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#91]
Two considerations: 

1) we already have an `st_dimension` which gets the dimension of vector features
2) users coming from python may be quite familiar with `shape` as the name of the attribute of an array to get its number of rows and columns.

Consider providing a SQL function `rf_shape` which takes a Tile and returns a tuple of ints or struct of two ints.

Possibly make `shape` available in python and scala APIs.

**Comment by metasim** [comment]
Now called `rf_dimensions`.
