### ISSUE TITLE
`any` and `all` type tile functions

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#95]
Similar to numpy [any](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.any.html) and [all](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.all.html) provide method to evaluate if any value in the Tile evaluates to true (non-zero), or if all values do.

potential usage:

```sql
SELECT rf_any(rf_equal(tile1, tile2)) 
FROM df

-----------

SELECT month(datetime) as month, rf_all(rf_greater(tile1, tile2))
FROM df
GROUP BY month
```

**Comment by metasim** [comment]
https://github.com/locationtech/rasterframes/commit/cb9991388c8db35baf8b0df88cdc6a0c15351655
