### ISSUE TITLE
Python and SQL functions parity 

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#97]
Add SQL support for the following python functions:

* envelope
* array_to_tile
* assemble_tile
* with_no_data
* local_agg_no_data_cells
* rf_explode_tiles_sample

Add Python support for the following SQL functions:

* rf_is_no_data_tile

Normalize naming between equivalent functions:

* python local_agg_data_cells vs sql rf_local_agg_count
* python agg_no_data_cells vs sql rf_agg_stats.noDataCells
* python agg_data_cells vs sql rf_agg_stats.dataCells 
* python agg_mean vs sql rf_agg_stats.mean
* python local_less vs sql rf_less (vice rf_local_less) ; and variants thereof
* python local_greater vs sql rf_greater; and variants
* python local_equal vs sql rf_equal; and variants
* python local_unequal vs sql rf_unequal; and variants

**Comment by vpipkt** [comment]
I believe this needs another scrub through. Much of this is complete.

**Comment by metasim** [comment]
Pretty sure most of these are covered now.
